<template>
  <section id="introduction">
    <h2>INÍCIO</h2>
    <p>
      EXPERIENCIE UMA NOVA DESCOBERTA SOBRE ESTRUTURAS TÃO IMPORTANTES E PRESENTES EM NOSSO DIA A
      DIA
    </p>
    <p>AS CÉLULAS SÃO AS MENORES UNIDADES ESTRUTURAIS E FUNCIONAIS DOS SERES VIVOS, SENDO A BASE PARA
      A FORMAÇÃO DOS ÓRGÃOS E TECIDOS DO NOSSO CORPO, COM TAMBÉM, SÃO RESPONSÁVEIS POR REALIZAR AS
      FUNÇÕES ESSENCIAIS QUE SUSTENTAM TODOS OS ORGANISMOS, DESDE AS MAIS SIMPLES BACTÉRIAS ATÉ OS
      SERES HUMANOS</p>
  </section>
</template>
